import type { ArchiveEvent, Person, TrustedContact } from '../types/models';

export const INITIAL_PEOPLE: Person[] = [
  {
    id: '1',
    name: 'Arthur Pendelton',
    title: 'Patriarch',
    isDeceased: true,
    religion: true,
    disavowedFaith: false,
    relationshipStatus: 'none',
    lineageType: 'direct',
    emotionalConnections: [],
    notes: 'Founded the family business in 1952.',
    parentIds: [],
    childrenIds: ['3', '4'],
    partnerIds: ['2'],
  },
  {
    id: '2',
    name: 'Eleanor Pendelton',
    title: 'Matriarch',
    isDeceased: false,
    religion: true,
    disavowedFaith: false,
    relationshipStatus: 'close',
    lineageType: 'direct',
    emotionalConnections: ['3'],
    notes: 'Keeper of the family archives.',
    parentIds: [],
    childrenIds: ['3', '4'],
    partnerIds: ['1'],
  },
  {
    id: '3',
    name: 'Charles Pendelton',
    title: 'Eldest Son / CEO',
    isDeceased: false,
    religion: false,
    disavowedFaith: true,
    relationshipStatus: 'issues',
    lineageType: 'direct',
    emotionalConnections: ['2', '5'],
    notes: 'Currently managing the estate. Strained relationship with sibling.',
    parentIds: ['1', '2'],
    childrenIds: ['5'],
    partnerIds: [],
  },
  {
    id: '4',
    name: 'Victoria Vance',
    title: 'Daughter',
    isDeceased: false,
    religion: true,
    disavowedFaith: false,
    relationshipStatus: 'cut',
    lineageType: 'distant',
    emotionalConnections: [],
    notes: 'Moved away in 2010. Rarely visits.',
    parentIds: ['1', '2'],
    childrenIds: [],
    partnerIds: [],
  },
  {
    id: '5',
    name: 'Leo Pendelton',
    title: 'Grandson',
    isDeceased: false,
    religion: false,
    disavowedFaith: false,
    relationshipStatus: 'close',
    lineageType: 'direct',
    emotionalConnections: ['3'],
    notes: 'Attending university.',
    parentIds: ['3'],
    childrenIds: [],
    partnerIds: [],
  },
];

export const INITIAL_EVENTS: ArchiveEvent[] = [
  {
    id: 'e1',
    title: 'Company Handover',
    personIds: ['1'],
    date: '1998-05-12',
    description: 'Arthur stepped down as CEO.',
  },
  {
    id: 'e2',
    title: 'The Great Argument',
    personIds: ['3', '4'],
    date: '2010-11-03',
    description: 'Major falling out leading to Victoria leaving.',
  },
];

export const INITIAL_CONTACTS: TrustedContact[] = [
  {
    id: 'c1',
    name: 'Robert Hayes',
    relation: 'Family Lawyer',
    phone: '+1 (555) 019-2834',
    email: 'rhayes@law.example.com',
    notes: 'Handles all estate matters.',
  },
];

export const PERSON_POSITIONS: Record<string, { x: number; y: number }> = {
  '1': { x: 140, y: 60 },
  '2': { x: 360, y: 60 },
  '3': { x: 140, y: 220 },
  '4': { x: 360, y: 220 },
  '5': { x: 140, y: 380 },
};
